-- International content/broadcast attributes and synthetic rating fact table.
-- Every block is idempotent and can be executed more than once.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE STG_TMDB_MOVIE ADD ORIGIN_COUNTRY_CODE VARCHAR2(2)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE STG_TMDB_TV ADD ORIGIN_COUNTRY_CODE VARCHAR2(2)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DIM_CONTENT ADD ORIGIN_COUNTRY_CODE VARCHAR2(2)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE STG_TVMAZE_SCHEDULE ADD COUNTRY_CODE VARCHAR2(2)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DIM_CHANNEL ADD COUNTRY_CODE VARCHAR2(2)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE STG_USER_RATING (
      RATING_ID          NUMBER        NOT NULL,
      SOURCE             VARCHAR2(30)  NOT NULL,
      SOURCE_CONTENT_ID  NUMBER        NOT NULL,
      CONTENT_TYPE       VARCHAR2(20)  NOT NULL,
      USER_ID            VARCHAR2(36)  NOT NULL,
      COUNTRY_CODE       VARCHAR2(2),
      RATING             NUMBER(3,1)   NOT NULL,
      RATED_AT           DATE          NOT NULL,
      IS_SYNTHETIC       NUMBER(1)     DEFAULT 1 NOT NULL,
      LOAD_DATE          DATE,
      CONSTRAINT PK_STG_USER_RATING PRIMARY KEY (RATING_ID),
      CONSTRAINT CK_STG_USER_RATING_VALUE CHECK (RATING BETWEEN 1 AND 10),
      CONSTRAINT CK_STG_USER_RATING_SYNTH CHECK (IS_SYNTHETIC IN (0, 1))
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE FACT_USER_RATING (
      RATING_KEY         NUMBER        NOT NULL,
      SOURCE_RATING_ID   NUMBER        NOT NULL,
      CONTENT_KEY        NUMBER        NOT NULL,
      DATE_KEY           NUMBER        NOT NULL,
      USER_ID            VARCHAR2(36)  NOT NULL,
      COUNTRY_CODE       VARCHAR2(2),
      RATING             NUMBER(3,1)   NOT NULL,
      RATED_AT           DATE          NOT NULL,
      IS_SYNTHETIC       NUMBER(1)     DEFAULT 1 NOT NULL,
      LOAD_DATE          DATE,
      CONSTRAINT PK_FACT_USER_RATING PRIMARY KEY (RATING_KEY),
      CONSTRAINT UQ_FACT_USER_RATING_SOURCE UNIQUE (SOURCE_RATING_ID),
      CONSTRAINT FK_FUR_CONTENT FOREIGN KEY (CONTENT_KEY)
        REFERENCES DIM_CONTENT (CONTENT_KEY),
      CONSTRAINT FK_FUR_DATE FOREIGN KEY (DATE_KEY)
        REFERENCES DIM_DATE (DATE_KEY),
      CONSTRAINT CK_FACT_USER_RATING_VALUE CHECK (RATING BETWEEN 1 AND 10),
      CONSTRAINT CK_FACT_USER_RATING_SYNTH CHECK (IS_SYNTHETIC IN (0, 1))
    )
  ]';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_FACT_USER_RATING START WITH 1 INCREMENT BY 1 NOCACHE';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

CREATE OR REPLACE TRIGGER BI_FACT_USER_RATING
BEFORE INSERT ON FACT_USER_RATING
FOR EACH ROW
WHEN (NEW.RATING_KEY IS NULL)
BEGIN
  :NEW.RATING_KEY := SEQ_FACT_USER_RATING.NEXTVAL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX IX_FUR_CONTENT_DATE ON FACT_USER_RATING (CONTENT_KEY, DATE_KEY)';
EXCEPTION WHEN OTHERS THEN
  IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- Before the multi-country extractor, every TMDB row was requested with TR.
-- Backfill those legacy records so the country analysis has no unknown bucket.
UPDATE STG_TMDB_MOVIE
SET ORIGIN_COUNTRY_CODE = 'TR'
WHERE ORIGIN_COUNTRY_CODE IS NULL
/

UPDATE STG_TMDB_TV
SET ORIGIN_COUNTRY_CODE = 'TR'
WHERE ORIGIN_COUNTRY_CODE IS NULL
/

MERGE INTO DIM_DATE target
USING (
  SELECT
    TO_NUMBER(TO_CHAR(full_date, 'YYYYMMDD')) AS date_key,
    full_date,
    TO_NUMBER(TO_CHAR(full_date, 'DD')) AS day_number,
    INITCAP(TRIM(TO_CHAR(full_date, 'Day', 'NLS_DATE_LANGUAGE=Turkish'))) AS day_name,
    TO_NUMBER(TO_CHAR(full_date, 'MM')) AS month_number,
    INITCAP(TRIM(TO_CHAR(full_date, 'Month', 'NLS_DATE_LANGUAGE=Turkish'))) AS month_name,
    TO_NUMBER(TO_CHAR(full_date, 'Q')) AS quarter_number,
    TO_NUMBER(TO_CHAR(full_date, 'YYYY')) AS year_number,
    CASE WHEN TO_CHAR(full_date, 'DY', 'NLS_DATE_LANGUAGE=English') IN ('SAT', 'SUN')
         THEN 1 ELSE 0 END AS is_weekend
  FROM (
    SELECT TRUNC(SYSDATE) - 364 + LEVEL - 1 AS full_date
    FROM dual
    CONNECT BY LEVEL <= 395
  )
) source
ON (target.date_key = source.date_key)
WHEN NOT MATCHED THEN INSERT (
  DATE_KEY, FULL_DATE, DAY_NUMBER, DAY_NAME, MONTH_NUMBER,
  MONTH_NAME, QUARTER_NUMBER, YEAR_NUMBER, IS_WEEKEND
) VALUES (
  source.date_key, source.full_date, source.day_number, source.day_name,
  source.month_number, source.month_name, source.quarter_number,
  source.year_number, source.is_weekend
)
/

COMMIT
/
