-- All user ratings in this project are synthetic demo data.

-- 1. Content catalogue by origin country and type
SELECT
  ORIGIN_COUNTRY_CODE,
  CONTENT_TYPE,
  COUNT(*) AS CONTENT_COUNT
FROM DIM_CONTENT
GROUP BY ORIGIN_COUNTRY_CODE, CONTENT_TYPE
ORDER BY ORIGIN_COUNTRY_CODE, CONTENT_TYPE;

-- 2. Synthetic rating behaviour by user country
SELECT
  COUNTRY_CODE AS USER_COUNTRY_CODE,
  COUNT(*) AS RATING_COUNT,
  COUNT(DISTINCT USER_ID) AS UNIQUE_USERS,
  ROUND(AVG(RATING), 2) AS AVG_RATING
FROM FACT_USER_RATING
WHERE IS_SYNTHETIC = 1
GROUP BY COUNTRY_CODE
ORDER BY RATING_COUNT DESC;

-- 3. Most-rated content and comparison with the TMDB score
SELECT
  content.TITLE,
  content.CONTENT_TYPE,
  content.ORIGIN_COUNTRY_CODE,
  COUNT(rating.RATING_KEY) AS RATING_COUNT,
  ROUND(AVG(rating.RATING), 2) AS SYNTHETIC_AVG_RATING,
  ROUND(AVG(metric.VOTE_AVERAGE), 2) AS TMDB_AVG_RATING
FROM FACT_USER_RATING rating
JOIN DIM_CONTENT content
  ON content.CONTENT_KEY = rating.CONTENT_KEY
LEFT JOIN FACT_CONTENT_METRICS metric
  ON metric.CONTENT_KEY = content.CONTENT_KEY
WHERE rating.IS_SYNTHETIC = 1
GROUP BY content.TITLE, content.CONTENT_TYPE, content.ORIGIN_COUNTRY_CODE
ORDER BY RATING_COUNT DESC
FETCH FIRST 20 ROWS ONLY;

-- 4. Broadcast volume by channel country
SELECT
  channel.COUNTRY_CODE,
  COUNT(*) AS BROADCAST_COUNT,
  ROUND(AVG(broadcast.RUNTIME), 2) AS AVG_RUNTIME_MIN
FROM FACT_BROADCAST broadcast
JOIN DIM_CHANNEL channel
  ON channel.CHANNEL_KEY = broadcast.CHANNEL_KEY
GROUP BY channel.COUNTRY_CODE
ORDER BY BROADCAST_COUNT DESC;

-- 5. Daily international broadcast trend
SELECT
  calendar.FULL_DATE,
  channel.COUNTRY_CODE,
  COUNT(*) AS BROADCAST_COUNT
FROM FACT_BROADCAST broadcast
JOIN DIM_DATE calendar
  ON calendar.DATE_KEY = broadcast.DATE_KEY
JOIN DIM_CHANNEL channel
  ON channel.CHANNEL_KEY = broadcast.CHANNEL_KEY
GROUP BY calendar.FULL_DATE, channel.COUNTRY_CODE
ORDER BY calendar.FULL_DATE, channel.COUNTRY_CODE;
